"use server"

/**
 * Session management Server Actions.
 *
 * The `sessions` table has REVOKE INSERT/UPDATE/DELETE for
 * authenticated/anon. All writes go through SECURITY DEFINER RPCs:
 *   - `create_session` — inserts, validates ownership/conflict/aal2
 *   - `cancel_session` — controlled state transition
 *   - `reschedule_session` — updates scheduled_at, validates conflict
 *
 * The RPCs derive psychologist_id from auth.uid() internally — never
 * accept it as a parameter (same vector as the Security Review
 * flagged on create-charge).
 *
 * room_name is generated by the database DEFAULT. The trigger
 * fn_sessions_on_reschedule regenerates it when scheduled_at changes.
 *
 * App-side conflict checks exist for better UI feedback (showing which
 * patient conflicts). The RPC is the guarantee — if the app check and
 * the RPC disagree, the RPC wins and the user sees a mapped error.
 *
 * @see architecture.md §6, §18
 * @see data-architecture.md §sessions
 * @see ADR-0002
 */

import { revalidatePath } from "next/cache"

import { withPsychologist, withPatient } from "@/lib/actions/_guard"
import { logAudit } from "@/lib/audit"
import { logError, logInfo } from "@/lib/logger"
import {
  createSessionSchema,
  cancelSessionSchema,
  rescheduleSessionSchema,
  sanitizeCancellationReason,
  type CreateSessionInput,
  type CancelSessionInput,
  type RescheduleSessionInput,
} from "@/schemas/session"

/**
 * Brazil timezone — all schedule calculations use this explicitly.
 * Never depend on server timezone.
 */
const BRAZIL_TZ = "America/Sao_Paulo"

/**
 * Format a date to ISO 8601 string with Brazil offset for timestamptz.
 *
 * Hardcodes -03:00 (BRT). Brazil abolished daylight saving time in 2019
 * (Decreto 9.772/2019), so America/Sao_Paulo is permanently UTC-3.
 * If DST is ever reinstated, this function must use Intl to resolve
 * the offset dynamically for the given date.
 */
function toUTCTimestamp(dateStr: string, timeStr: string): string {
  const [hours, minutes] = timeStr.split(":").map(Number)
  return `${dateStr}T${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:00-03:00`
}

/**
 * Get the next occurrence of a specific day_of_week from a start date.
 * day_of_week: 0=Sunday, 1=Monday, ..., 6=Saturday
 */
function getNextDayOfWeek(startDate: string, dayOfWeek: number): Date {
  const date = new Date(startDate + "T12:00:00") // noon to avoid timezone issues
  const currentDay = date.getDay()
  let daysUntil = dayOfWeek - currentDay
  if (daysUntil < 0) daysUntil += 7
  if (daysUntil === 0 && date <= new Date()) daysUntil = 7
  date.setDate(date.getDate() + daysUntil)
  return date
}

/**
 * Format a Date to YYYY-MM-DD string.
 */
function formatDate(date: Date): string {
  return date.toISOString().split("T")[0]
}

/**
 * Check if two time ranges overlap.
 * Each range is [start, start + duration_minutes).
 */
function rangesOverlap(
  startA: Date,
  durationA: number,
  startB: Date,
  durationB: number,
): boolean {
  const endA = new Date(startA.getTime() + durationA * 60_000)
  const endB = new Date(startB.getTime() + durationB * 60_000)
  return startA < endB && startB < endA
}

interface ConflictInfo {
  patientName: string
  startTime: string
  endTime: string
}

/**
 * Map a PostgreSQL RPC error message to a user-facing pt-BR message.
 *
 * The RPCs raise generic exceptions by security design. We classify
 * them here for the UI. If none of the known patterns match, a safe
 * fallback is returned.
 */
function mapRpcError(errorMessage: string, fallback: string): string {
  const msg = (errorMessage ?? "").toLowerCase()

  if (msg.includes("conflict") || msg.includes("overlap") || msg.includes("already exists"))
    return "Ja existe uma sessao nesse horario."
  if (msg.includes("not found") || msg.includes("session not found"))
    return "Sessao nao encontrada."
  if (msg.includes("not authenticated") || msg.includes("not auth"))
    return "Nao autenticado."
  if (msg.includes("not your") || msg.includes("not authorized") || msg.includes("permission"))
    return "Sem permissao para esta operacao."
  if (msg.includes("status") || msg.includes("cannot be"))
    return "Esta sessao nao pode ser modificada no estado atual."
  if (msg.includes("past") || msg.includes("future"))
    return "Nao e possivel agendar para uma data passada."
  if (msg.includes("duration"))
    return "Duracao invalida."
  if (msg.includes("patient") && msg.includes("belong"))
    return "Paciente nao pertence a esta psicologa."

  return fallback
}

/**
 * Create a session (single or recurring).
 *
 * For recurring sessions, generates 12 weekly occurrences.
 * Each occurrence calls the `create_session` RPC individually.
 * Partial creation: if some slots fail (conflict in the RPC),
 * the rest are created and the user gets a warning.
 *
 * App-side conflict check provides better UI feedback (which patient
 * conflicts). The RPC is the authoritative guarantee.
 */
export const createSession = withPsychologist(
  async (ctx, input: CreateSessionInput) => {
    const parsed = createSessionSchema.parse(input)

    // Verify the patient belongs to this psychologist (for display name)
    const { data: patient } = await ctx.supabase
      .from("patients")
      .select("id, full_name")
      .eq("id", parsed.patient_id)
      .single()

    if (!patient) {
      throw new Error("Paciente nao encontrado")
    }

    // Generate dates for all occurrences
    const dates: string[] = []
    const firstDate = getNextDayOfWeek(parsed.start_date, parsed.day_of_week)

    if (parsed.is_recurring) {
      for (let i = 0; i < 12; i++) {
        const d = new Date(firstDate)
        d.setDate(d.getDate() + i * 7)
        dates.push(formatDate(d))
      }
    } else {
      dates.push(formatDate(firstDate))
    }

    // App-side conflict check for UI feedback (who conflicts, at what time)
    const startOfRange = dates[0]
    const endOfRange = dates[dates.length - 1]

    const { data: existingSessions } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, duration_minutes, patient_id")
      .eq("psychologist_id", ctx.profileId)
      .gte("scheduled_at", `${startOfRange}T00:00:00`)
      .lte("scheduled_at", `${endOfRange}T23:59:59`)
      .in("status", ["scheduled", "confirmed", "in_progress"])

    // Look up patient names for conflict messages
    const conflictPatientIds = new Set(
      (existingSessions ?? []).map((s) => s.patient_id),
    )
    const patientNames = new Map<string, string>()
    if (conflictPatientIds.size > 0) {
      const { data: patients } = await ctx.supabase
        .from("patients")
        .select("id, full_name")
        .in("id", Array.from(conflictPatientIds))

      if (patients) {
        for (const p of patients) {
          patientNames.set(p.id, p.full_name)
        }
      }
    }

    // Build the list of timestamps and app-side conflict info
    const recurrenceGroupId =
      parsed.is_recurring ? crypto.randomUUID() : null
    const createdDates: string[] = []
    const conflicts: ConflictInfo[] = []
    const rpcFailures: string[] = []

    for (const dateStr of dates) {
      const scheduledAt = toUTCTimestamp(dateStr, parsed.time)
      const scheduledDate = new Date(scheduledAt)

      // App-side conflict check for UI feedback
      let appSideConflict: ConflictInfo | null = null
      for (const existing of existingSessions ?? []) {
        const existingStart = new Date(existing.scheduled_at)
        if (
          rangesOverlap(
            scheduledDate,
            parsed.duration_minutes,
            existingStart,
            existing.duration_minutes,
          )
        ) {
          const endTime = new Date(
            existingStart.getTime() +
              existing.duration_minutes * 60_000,
          )
          const formatter = new Intl.DateTimeFormat("pt-BR", {
            timeZone: BRAZIL_TZ,
            hour: "2-digit",
            minute: "2-digit",
          })
          appSideConflict = {
            patientName:
              patientNames.get(existing.patient_id) || "Paciente",
            startTime: formatter.format(existingStart),
            endTime: formatter.format(endTime),
          }
          break
        }
      }

      if (appSideConflict) {
        // Skip known conflicts (avoid unnecessary RPC call)
        conflicts.push(appSideConflict)
        continue
      }

      // Call the RPC — the guarantee. No p_psychologist_id: derived from auth.uid().
      const { data: sessionId, error: rpcError } = await ctx.supabase.rpc(
        "create_session",
        {
          p_patient_id: parsed.patient_id,
          p_scheduled_at: scheduledAt,
          p_duration_minutes: parsed.duration_minutes,
          p_recurrence_group_id: recurrenceGroupId,
        },
      )

      if (rpcError) {
        // RPC rejected — likely a conflict the app-side check missed
        // (race condition or different exclusion criteria)
        const mapped = mapRpcError(
          rpcError.message,
          "Nao foi possivel criar a sessao",
        )
        if (mapped.includes("horario")) {
          conflicts.push({
            patientName: "Paciente",
            startTime: parsed.time,
            endTime: "--:--",
          })
        } else {
          rpcFailures.push(`${dateStr}: ${mapped}`)
        }
        continue
      }

      createdDates.push(dateStr)

      // Audit
      await logAudit(ctx.supabase, parsed.patient_id, "CREATE_SESSION", {
        session_date: dateStr,
      })
    }

    if (createdDates.length === 0) {
      const conflictMsg = conflicts
        .map(
          (c) =>
            `Conflito com sessao de ${c.patientName} das ${c.startTime} as ${c.endTime}`,
        )
        .join("; ")
      const failureMsg = rpcFailures.join("; ")
      throw new Error(
        conflictMsg || failureMsg || "Todos os horarios tem conflito",
      )
    }

    logInfo({
      event_type: "sessions_created",
      action: "CREATE_SESSION",
      patient_id: parsed.patient_id,
    })

    revalidatePath("/agenda")

    return {
      created: createdDates.length,
      total: dates.length,
      conflicts,
    }
  },
)

/**
 * Cancel a session — delegates to RPC cancel_session.
 *
 * The RPC validates ownership, status, and timing constraints.
 * DoD-2: cancellation_reason is sanitized before passing to the RPC.
 *
 * Late cancellation policy:
 * - Cancellation within policy hours → normal
 * - Cancellation outside policy hours → reason prefixed with [FORA DO PRAZO],
 *   passed to the RPC so the DB stores it. The RPC writes cancellation_reason.
 */
export const cancelSession = withPsychologist(
  async (ctx, input: CancelSessionInput) => {
    const parsed = cancelSessionSchema.parse(input)

    // Sanitize reason (DoD-2)
    const sanitizedReason = parsed.reason
      ? sanitizeCancellationReason(parsed.reason)
      : null

    // Get session details for policy check
    const { data: session } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, patient_id, status")
      .eq("id", parsed.session_id)
      .eq("psychologist_id", ctx.profileId)
      .single()

    if (!session) {
      throw new Error("Sessao nao encontrada")
    }

    // Check cancellation policy timing
    const { data: profile } = await ctx.supabase
      .from("profiles")
      .select("cancellation_policy_hours")
      .eq("id", ctx.profileId)
      .single()

    const policyHours = profile?.cancellation_policy_hours ?? 24
    const sessionTime = new Date(session.scheduled_at)
    const now = new Date()
    const hoursUntilSession =
      (sessionTime.getTime() - now.getTime()) / (1000 * 60 * 60)
    const isLateCancellation = hoursUntilSession < policyHours

    // Build the reason with late-cancellation prefix if applicable.
    // The RPC writes cancellation_reason — no need to UPDATE separately.
    const finalReason = isLateCancellation
      ? sanitizedReason
        ? `[FORA DO PRAZO] ${sanitizedReason}`
        : "[FORA DO PRAZO]"
      : sanitizedReason

    // Call the RPC (validates ownership, status, timing in the DB)
    const { error } = await ctx.supabase.rpc("cancel_session", {
      p_session_id: parsed.session_id,
      p_reason: finalReason,
    })

    if (error) {
      logError({
        event_type: "session_cancel_failure",
        session_id: parsed.session_id,
        action: "CANCEL_SESSION",
        error_code: "RPC_FAILED",
      })
      throw new Error(
        mapRpcError(error.message, "Nao foi possivel cancelar a sessao"),
      )
    }

    await logAudit(
      ctx.supabase,
      session.patient_id,
      "CANCEL_SESSION",
      {
        late_cancellation: isLateCancellation,
        hours_before: Math.round(hoursUntilSession),
      },
    )

    logInfo({
      event_type: "session_cancelled",
      session_id: parsed.session_id,
      action: "CANCEL_SESSION",
    })

    revalidatePath("/agenda")
    revalidatePath("/portal")

    return { isLateCancellation }
  },
)

/**
 * Cancel a session as a patient — delegates to same RPC.
 * The RPC checks patient ownership via patients.user_id.
 */
export const cancelSessionAsPatient = withPatient(
  async (ctx, input: CancelSessionInput) => {
    const parsed = cancelSessionSchema.parse(input)

    const sanitizedReason = parsed.reason
      ? sanitizeCancellationReason(parsed.reason)
      : null

    // Get session for policy check
    const { data: session } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, psychologist_id, status")
      .eq("id", parsed.session_id)
      .eq("patient_id", ctx.patientId)
      .single()

    if (!session) {
      throw new Error("Sessao nao encontrada")
    }

    // Get cancellation policy from psychologist's profile
    const { data: psychProfile } = await ctx.supabase
      .from("profiles")
      .select("cancellation_policy_hours")
      .eq("id", session.psychologist_id)
      .single()

    const policyHours = psychProfile?.cancellation_policy_hours ?? 24
    const sessionTime = new Date(session.scheduled_at)
    const now = new Date()
    const hoursUntilSession =
      (sessionTime.getTime() - now.getTime()) / (1000 * 60 * 60)
    const isLateCancellation = hoursUntilSession < policyHours

    // Build the reason with late-cancellation prefix
    const finalReason = isLateCancellation
      ? sanitizedReason
        ? `[FORA DO PRAZO] ${sanitizedReason}`
        : "[FORA DO PRAZO]"
      : sanitizedReason

    const { error } = await ctx.supabase.rpc("cancel_session", {
      p_session_id: parsed.session_id,
      p_reason: finalReason,
    })

    if (error) {
      logError({
        event_type: "session_cancel_failure",
        session_id: parsed.session_id,
        action: "CANCEL_SESSION",
        error_code: "RPC_FAILED",
      })
      throw new Error(
        mapRpcError(error.message, "Nao foi possivel cancelar a sessao"),
      )
    }

    await logAudit(
      ctx.supabase,
      ctx.patientId,
      "CANCEL_SESSION",
      {
        late_cancellation: isLateCancellation,
        hours_before: Math.round(hoursUntilSession),
      },
    )

    logInfo({
      event_type: "session_cancelled",
      session_id: parsed.session_id,
      action: "CANCEL_SESSION",
    })

    revalidatePath("/portal")
    revalidatePath("/agenda")

    return { isLateCancellation }
  },
)

/**
 * Reschedule a session — delegates to RPC reschedule_session.
 *
 * The RPC validates:
 * - Authentication, psychologist role, aal2
 * - Session ownership
 * - Status (only scheduled/confirmed)
 * - Future date
 * - Conflict with other sessions
 *
 * The trigger fn_sessions_on_reschedule handles:
 * - Regenerating room_name
 * - Clearing waiting_since and admitted_at
 *
 * App-side conflict check exists for UI feedback (showing which
 * patient conflicts). The RPC is the guarantee.
 */
export const rescheduleSession = withPsychologist(
  async (ctx, input: RescheduleSessionInput) => {
    const parsed = rescheduleSessionSchema.parse(input)

    // Get current session for audit trail and UI pre-check
    const { data: session } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, duration_minutes, patient_id, status")
      .eq("id", parsed.session_id)
      .eq("psychologist_id", ctx.profileId)
      .single()

    if (!session) {
      throw new Error("Sessao nao encontrada")
    }

    if (!["scheduled", "confirmed"].includes(session.status)) {
      throw new Error("Sessao nao pode ser remarcada no estado atual")
    }

    const newScheduledAt = toUTCTimestamp(
      parsed.new_date,
      parsed.new_time,
    )
    const newStart = new Date(newScheduledAt)

    // App-side: prevent rescheduling to the past (better UX than RPC error)
    if (newStart < new Date()) {
      throw new Error("Nao e possivel remarcar para uma data passada")
    }

    // App-side conflict check for UI feedback
    const { data: existingSessions } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, duration_minutes, patient_id")
      .eq("psychologist_id", ctx.profileId)
      .neq("id", parsed.session_id)
      .gte("scheduled_at", `${parsed.new_date}T00:00:00`)
      .lte("scheduled_at", `${parsed.new_date}T23:59:59`)
      .in("status", ["scheduled", "confirmed", "in_progress"])

    for (const existing of existingSessions ?? []) {
      const existingStart = new Date(existing.scheduled_at)
      if (
        rangesOverlap(
          newStart,
          session.duration_minutes,
          existingStart,
          existing.duration_minutes,
        )
      ) {
        const { data: conflictPatient } = await ctx.supabase
          .from("patients")
          .select("full_name")
          .eq("id", existing.patient_id)
          .single()

        const formatter = new Intl.DateTimeFormat("pt-BR", {
          timeZone: BRAZIL_TZ,
          hour: "2-digit",
          minute: "2-digit",
        })
        const endTime = new Date(
          existingStart.getTime() + existing.duration_minutes * 60_000,
        )
        throw new Error(
          `Conflito com sessao de ${conflictPatient?.full_name || "Paciente"} das ${formatter.format(existingStart)} as ${formatter.format(endTime)}`,
        )
      }
    }

    // Call the RPC — the guarantee. No p_psychologist_id.
    const { error } = await ctx.supabase.rpc("reschedule_session", {
      p_session_id: parsed.session_id,
      p_new_scheduled_at: newScheduledAt,
    })

    if (error) {
      logError({
        event_type: "session_reschedule_failure",
        session_id: parsed.session_id,
        action: "RESCHEDULE_SESSION",
        error_code: "RPC_FAILED",
      })
      throw new Error(
        mapRpcError(
          error.message,
          "Nao foi possivel remarcar a sessao",
        ),
      )
    }

    await logAudit(
      ctx.supabase,
      session.patient_id,
      "RESCHEDULE_SESSION",
      {
        old_date: session.scheduled_at,
        new_date: newScheduledAt,
      },
    )

    logInfo({
      event_type: "session_rescheduled",
      session_id: parsed.session_id,
      action: "RESCHEDULE_SESSION",
    })

    revalidatePath("/agenda")
    revalidatePath("/portal")

    return undefined
  },
)

/**
 * Get sessions for the psychologist's schedule.
 *
 * Not a Server Action — called from Server Components.
 * Uses the authenticated client (RLS applies).
 */
export async function getScheduleSessions(
  supabase: import("@supabase/supabase-js").SupabaseClient,
  psychologistId: string,
  startDate: string,
  endDate: string,
) {
  const { data, error } = await supabase
    .from("sessions")
    .select(
      "id, patient_id, scheduled_at, duration_minutes, status, payment_status, recurrence_group_id, cancelled_at, cancelled_by",
    )
    .eq("psychologist_id", psychologistId)
    .gte("scheduled_at", `${startDate}T00:00:00`)
    .lte("scheduled_at", `${endDate}T23:59:59`)
    .order("scheduled_at", { ascending: true })

  if (error) {
    logError({
      event_type: "schedule_fetch_failure",
      action: "getScheduleSessions",
      error_code: "QUERY_FAILED",
    })
    return []
  }

  return data ?? []
}
