"use server"

/**
 * Session management Server Actions.
 *
 * IMPORTANT: The `sessions` table has REVOKE INSERT/UPDATE/DELETE for
 * authenticated/anon. All writes go through:
 *   - Admin client (service_role) for INSERTs — in the allowlist because
 *     this is analogous to patient creation (admin-only write).
 *   - RPC `cancel_session` for cancellations (existing).
 *   - New RPCs will be needed for reschedule (reported in summary).
 *
 * room_name is generated by the database DEFAULT. The trigger
 * fn_sessions_on_reschedule regenerates it when scheduled_at changes.
 *
 * @see architecture.md §6, §18
 * @see data-architecture.md §sessions
 * @see ADR-0002
 */

import { revalidatePath } from "next/cache"

import { withPsychologist, withPatient } from "@/lib/actions/_guard"
import { createAdminClient } from "@/lib/supabase/admin"
import { logAudit, type AuditAction } from "@/lib/audit"
import { logError, logInfo } from "@/lib/logger"
import {
  createSessionSchema,
  cancelSessionSchema,
  rescheduleSessionSchema,
  sanitizeCancellationReason,
  type CreateSessionInput,
  type CancelSessionInput,
  type RescheduleSessionInput,
} from "@/schemas/session"

/**
 * Brazil timezone — all schedule calculations use this explicitly.
 * Never depend on server timezone.
 */
const BRAZIL_TZ = "America/Sao_Paulo"

/**
 * Format a date to ISO 8601 string in UTC for timestamptz.
 */
function toUTCTimestamp(dateStr: string, timeStr: string): string {
  // Parse as Brazil time, then let the DB store as timestamptz (UTC)
  // We create the date in the Brazil timezone explicitly
  const [hours, minutes] = timeStr.split(":").map(Number)
  const date = new Date(`${dateStr}T${timeStr}:00`)

  // Get the Brazil offset for this specific date/time
  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone: BRAZIL_TZ,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  })

  // Build the timestamptz using explicit Brazil timezone
  // The DB stores timestamptz in UTC automatically
  return `${dateStr}T${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:00-03:00`
}

/**
 * Get the next occurrence of a specific day_of_week from a start date.
 * day_of_week: 0=Sunday, 1=Monday, ..., 6=Saturday
 */
function getNextDayOfWeek(startDate: string, dayOfWeek: number): Date {
  const date = new Date(startDate + "T12:00:00") // noon to avoid timezone issues
  const currentDay = date.getDay()
  let daysUntil = dayOfWeek - currentDay
  if (daysUntil < 0) daysUntil += 7
  if (daysUntil === 0 && date <= new Date()) daysUntil = 7
  date.setDate(date.getDate() + daysUntil)
  return date
}

/**
 * Format a Date to YYYY-MM-DD string.
 */
function formatDate(date: Date): string {
  return date.toISOString().split("T")[0]
}

/**
 * Check if two time ranges overlap.
 * Each range is [start, start + duration_minutes).
 */
function rangesOverlap(
  startA: Date,
  durationA: number,
  startB: Date,
  durationB: number,
): boolean {
  const endA = new Date(startA.getTime() + durationA * 60_000)
  const endB = new Date(startB.getTime() + durationB * 60_000)
  return startA < endB && startB < endA
}

interface ConflictInfo {
  patientName: string
  startTime: string
  endTime: string
}

/**
 * Create a session (single or recurring).
 *
 * For recurring sessions, generates 12 weekly occurrences.
 * Partial creation: if some slots conflict, creates the rest + warning.
 *
 * Uses admin client because sessions has REVOKE INSERT for authenticated.
 * room_name is generated by the database DEFAULT.
 */
export const createSession = withPsychologist(
  async (ctx, input: CreateSessionInput) => {
    const parsed = createSessionSchema.parse(input)

    const admin = createAdminClient()

    // Verify the patient belongs to this psychologist
    const { data: patient } = await ctx.supabase
      .from("patients")
      .select("id, full_name")
      .eq("id", parsed.patient_id)
      .single()

    if (!patient) {
      throw new Error("Paciente nao encontrado")
    }

    // Generate dates for all occurrences
    const dates: string[] = []
    const firstDate = getNextDayOfWeek(parsed.start_date, parsed.day_of_week)

    if (parsed.is_recurring) {
      for (let i = 0; i < 12; i++) {
        const d = new Date(firstDate)
        d.setDate(d.getDate() + i * 7)
        dates.push(formatDate(d))
      }
    } else {
      dates.push(formatDate(firstDate))
    }

    // Check conflicts for all dates
    const startOfRange = dates[0]
    const endOfRange = dates[dates.length - 1]

    const { data: existingSessions } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, duration_minutes, patient_id")
      .eq("psychologist_id", ctx.profileId)
      .gte("scheduled_at", `${startOfRange}T00:00:00`)
      .lte("scheduled_at", `${endOfRange}T23:59:59`)
      .in("status", ["scheduled", "confirmed", "in_progress"])

    // Look up patient names for conflict messages
    const conflictPatientIds = new Set(
      (existingSessions ?? []).map((s) => s.patient_id),
    )
    const patientNames = new Map<string, string>()
    if (conflictPatientIds.size > 0) {
      const { data: patients } = await ctx.supabase
        .from("patients")
        .select("id, full_name")
        .in("id", Array.from(conflictPatientIds))

      if (patients) {
        for (const p of patients) {
          patientNames.set(p.id, p.full_name)
        }
      }
    }

    // Determine which dates are conflict-free
    const createdDates: string[] = []
    const conflicts: ConflictInfo[] = []
    const recurrenceGroupId =
      parsed.is_recurring ? crypto.randomUUID() : null

    for (const dateStr of dates) {
      const scheduledAt = new Date(
        toUTCTimestamp(dateStr, parsed.time),
      )

      let hasConflict = false
      for (const existing of existingSessions ?? []) {
        const existingStart = new Date(existing.scheduled_at)
        if (
          rangesOverlap(
            scheduledAt,
            parsed.duration_minutes,
            existingStart,
            existing.duration_minutes,
          )
        ) {
          const endTime = new Date(
            existingStart.getTime() +
              existing.duration_minutes * 60_000,
          )
          const formatter = new Intl.DateTimeFormat("pt-BR", {
            timeZone: BRAZIL_TZ,
            hour: "2-digit",
            minute: "2-digit",
          })
          conflicts.push({
            patientName:
              patientNames.get(existing.patient_id) || "Paciente",
            startTime: formatter.format(existingStart),
            endTime: formatter.format(endTime),
          })
          hasConflict = true
          break
        }
      }

      if (!hasConflict) {
        createdDates.push(dateStr)
      }
    }

    if (createdDates.length === 0) {
      const conflictMsg = conflicts
        .map(
          (c) =>
            `Conflito com sessao de ${c.patientName} das ${c.startTime} as ${c.endTime}`,
        )
        .join("; ")
      throw new Error(conflictMsg || "Todos os horarios tem conflito")
    }

    // Insert sessions via admin client
    const rows = createdDates.map((dateStr) => ({
      patient_id: parsed.patient_id,
      psychologist_id: ctx.profileId,
      scheduled_at: toUTCTimestamp(dateStr, parsed.time),
      duration_minutes: parsed.duration_minutes,
      status: "scheduled" as const,
      recurrence_group_id: recurrenceGroupId,
    }))

    const { error: insertError } = await admin
      .from("sessions")
      .insert(rows)

    if (insertError) {
      logError({
        event_type: "session_create_failure",
        action: "CREATE_SESSION",
        error_code: "INSERT_FAILED",
      })
      throw new Error("Nao foi possivel criar a sessao")
    }

    // Audit
    for (const dateStr of createdDates) {
      await logAudit(ctx.supabase, parsed.patient_id, "CREATE_RECORD" as AuditAction, {
        session_date: dateStr,
      })
    }

    logInfo({
      event_type: "sessions_created",
      action: "CREATE_SESSION",
      patient_id: parsed.patient_id,
    })

    revalidatePath("/agenda")

    // Build result
    const result: {
      created: number
      total: number
      conflicts: ConflictInfo[]
    } = {
      created: createdDates.length,
      total: dates.length,
      conflicts,
    }

    return result
  },
)

/**
 * Cancel a session — delegates to RPC cancel_session.
 *
 * The RPC validates ownership, status, and timing constraints.
 * DoD-2: cancellation_reason is sanitized before passing to the RPC.
 *
 * Also checks cancellation policy timing:
 * - Within policy hours → normal cancellation
 * - Outside policy hours → flag for billing (late_cancellation metadata)
 */
export const cancelSession = withPsychologist(
  async (ctx, input: CancelSessionInput) => {
    const parsed = cancelSessionSchema.parse(input)

    // Sanitize reason (DoD-2)
    const sanitizedReason = parsed.reason
      ? sanitizeCancellationReason(parsed.reason)
      : null

    // Get session details for policy check
    const { data: session } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, patient_id, status")
      .eq("id", parsed.session_id)
      .eq("psychologist_id", ctx.profileId)
      .single()

    if (!session) {
      throw new Error("Sessao nao encontrada")
    }

    // Check cancellation policy timing
    const { data: profile } = await ctx.supabase
      .from("profiles")
      .select("cancellation_policy_hours")
      .eq("id", ctx.profileId)
      .single()

    const policyHours = profile?.cancellation_policy_hours ?? 24
    const sessionTime = new Date(session.scheduled_at)
    const now = new Date()
    const hoursUntilSession =
      (sessionTime.getTime() - now.getTime()) / (1000 * 60 * 60)
    const isLateCancellation = hoursUntilSession < policyHours

    // Call the RPC (validates ownership, status, timing in the DB)
    const { error } = await ctx.supabase.rpc("cancel_session", {
      p_session_id: parsed.session_id,
      p_reason: sanitizedReason,
    })

    if (error) {
      logError({
        event_type: "session_cancel_failure",
        session_id: parsed.session_id,
        action: "CANCEL_SESSION",
        error_code: "RPC_FAILED",
      })
      throw new Error(
        error.message.includes("status")
          ? "Esta sessao nao pode ser cancelada no estado atual"
          : error.message.includes("passed")
            ? "Nao e possivel cancelar uma sessao que ja aconteceu"
            : "Nao foi possivel cancelar a sessao",
      )
    }

    // If late cancellation, mark metadata for billing (Sprint 5)
    if (isLateCancellation) {
      const admin = createAdminClient()
      await admin
        .from("sessions")
        .update({
          cancellation_reason: sanitizedReason
            ? `[FORA DO PRAZO] ${sanitizedReason}`
            : "[FORA DO PRAZO]",
        })
        .eq("id", parsed.session_id)
    }

    await logAudit(
      ctx.supabase,
      session.patient_id,
      "CANCEL_SESSION",
      {
        late_cancellation: isLateCancellation,
        hours_before: Math.round(hoursUntilSession),
      },
    )

    logInfo({
      event_type: "session_cancelled",
      session_id: parsed.session_id,
      action: "CANCEL_SESSION",
    })

    revalidatePath("/agenda")
    revalidatePath("/portal")

    return { isLateCancellation }
  },
)

/**
 * Cancel a session as a patient — delegates to same RPC.
 * The RPC checks patient ownership via patients.user_id.
 */
export const cancelSessionAsPatient = withPatient(
  async (ctx, input: CancelSessionInput) => {
    const parsed = cancelSessionSchema.parse(input)

    const sanitizedReason = parsed.reason
      ? sanitizeCancellationReason(parsed.reason)
      : null

    // Get session for policy check
    const { data: session } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, psychologist_id, status")
      .eq("id", parsed.session_id)
      .eq("patient_id", ctx.patientId)
      .single()

    if (!session) {
      throw new Error("Sessao nao encontrada")
    }

    // Get cancellation policy from psychologist's profile
    const { data: psychProfile } = await ctx.supabase
      .from("profiles")
      .select("cancellation_policy_hours")
      .eq("id", session.psychologist_id)
      .single()

    const policyHours = psychProfile?.cancellation_policy_hours ?? 24
    const sessionTime = new Date(session.scheduled_at)
    const now = new Date()
    const hoursUntilSession =
      (sessionTime.getTime() - now.getTime()) / (1000 * 60 * 60)
    const isLateCancellation = hoursUntilSession < policyHours

    const { error } = await ctx.supabase.rpc("cancel_session", {
      p_session_id: parsed.session_id,
      p_reason: sanitizedReason,
    })

    if (error) {
      logError({
        event_type: "session_cancel_failure",
        session_id: parsed.session_id,
        action: "CANCEL_SESSION",
        error_code: "RPC_FAILED",
      })
      throw new Error("Nao foi possivel cancelar a sessao")
    }

    // Mark late cancellation
    if (isLateCancellation) {
      const admin = createAdminClient()
      await admin
        .from("sessions")
        .update({
          cancellation_reason: sanitizedReason
            ? `[FORA DO PRAZO] ${sanitizedReason}`
            : "[FORA DO PRAZO]",
        })
        .eq("id", parsed.session_id)
    }

    await logAudit(
      ctx.supabase,
      ctx.patientId,
      "CANCEL_SESSION",
      {
        late_cancellation: isLateCancellation,
        hours_before: Math.round(hoursUntilSession),
      },
    )

    logInfo({
      event_type: "session_cancelled",
      session_id: parsed.session_id,
      action: "CANCEL_SESSION",
    })

    revalidatePath("/portal")
    revalidatePath("/agenda")

    return { isLateCancellation }
  },
)

/**
 * Reschedule a session.
 *
 * Implementation note: REVOKE UPDATE is applied to sessions for authenticated.
 * Rescheduling requires updating scheduled_at, which can only happen via
 * service_role or a SECURITY DEFINER RPC.
 *
 * The trigger fn_sessions_on_reschedule handles:
 * - Regenerating room_name
 * - Clearing waiting_since and admitted_at
 *
 * DECISION: Using admin client here. An RPC would be better for
 * validation encapsulation, but writing SQL is deferred to the
 * Data Architect (per task constraints). The needed RPC signature
 * is documented in the summary.
 */
export const rescheduleSession = withPsychologist(
  async (ctx, input: RescheduleSessionInput) => {
    const parsed = rescheduleSessionSchema.parse(input)

    // Get current session
    const { data: session } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, duration_minutes, patient_id, status")
      .eq("id", parsed.session_id)
      .eq("psychologist_id", ctx.profileId)
      .single()

    if (!session) {
      throw new Error("Sessao nao encontrada")
    }

    if (!["scheduled", "confirmed"].includes(session.status)) {
      throw new Error("Sessao nao pode ser remarcada no estado atual")
    }

    const newScheduledAt = toUTCTimestamp(
      parsed.new_date,
      parsed.new_time,
    )
    const newStart = new Date(newScheduledAt)

    // Prevent rescheduling to the past
    if (newStart < new Date()) {
      throw new Error("Nao e possivel remarcar para uma data passada")
    }

    // Check conflicts at new time
    const { data: existingSessions } = await ctx.supabase
      .from("sessions")
      .select("id, scheduled_at, duration_minutes, patient_id")
      .eq("psychologist_id", ctx.profileId)
      .neq("id", parsed.session_id) // Exclude current session
      .gte(
        "scheduled_at",
        `${parsed.new_date}T00:00:00`,
      )
      .lte(
        "scheduled_at",
        `${parsed.new_date}T23:59:59`,
      )
      .in("status", ["scheduled", "confirmed", "in_progress"])

    for (const existing of existingSessions ?? []) {
      const existingStart = new Date(existing.scheduled_at)
      if (
        rangesOverlap(
          newStart,
          session.duration_minutes,
          existingStart,
          existing.duration_minutes,
        )
      ) {
        // Get patient name for conflict message
        const { data: conflictPatient } = await ctx.supabase
          .from("patients")
          .select("full_name")
          .eq("id", existing.patient_id)
          .single()

        const formatter = new Intl.DateTimeFormat("pt-BR", {
          timeZone: BRAZIL_TZ,
          hour: "2-digit",
          minute: "2-digit",
        })
        const endTime = new Date(
          existingStart.getTime() + existing.duration_minutes * 60_000,
        )
        throw new Error(
          `Conflito com sessao de ${conflictPatient?.full_name || "Paciente"} das ${formatter.format(existingStart)} as ${formatter.format(endTime)}`,
        )
      }
    }

    // Update via admin client (REVOKE prevents authenticated from updating)
    // The trigger fn_sessions_on_reschedule will:
    // - Regenerate room_name
    // - Clear waiting_since and admitted_at
    const admin = createAdminClient()
    const { error } = await admin
      .from("sessions")
      .update({
        scheduled_at: newScheduledAt,
        status: "scheduled", // Reset to scheduled on reschedule
      })
      .eq("id", parsed.session_id)

    if (error) {
      logError({
        event_type: "session_reschedule_failure",
        session_id: parsed.session_id,
        action: "RESCHEDULE_SESSION",
        error_code: "UPDATE_FAILED",
      })
      throw new Error("Nao foi possivel remarcar a sessao")
    }

    await logAudit(
      ctx.supabase,
      session.patient_id,
      "RESCHEDULE_SESSION",
      {
        old_date: session.scheduled_at,
        new_date: newScheduledAt,
      },
    )

    logInfo({
      event_type: "session_rescheduled",
      session_id: parsed.session_id,
      action: "RESCHEDULE_SESSION",
    })

    revalidatePath("/agenda")
    revalidatePath("/portal")

    return undefined
  },
)

/**
 * Get sessions for the psychologist's schedule.
 *
 * Not a Server Action — called from Server Components.
 * Uses the authenticated client (RLS applies).
 */
export async function getScheduleSessions(
  supabase: import("@supabase/supabase-js").SupabaseClient,
  psychologistId: string,
  startDate: string,
  endDate: string,
) {
  const { data, error } = await supabase
    .from("sessions")
    .select(
      "id, patient_id, scheduled_at, duration_minutes, status, payment_status, recurrence_group_id, cancelled_at, cancelled_by",
    )
    .eq("psychologist_id", psychologistId)
    .gte("scheduled_at", `${startDate}T00:00:00`)
    .lte("scheduled_at", `${endDate}T23:59:59`)
    .order("scheduled_at", { ascending: true })

  if (error) {
    logError({
      event_type: "schedule_fetch_failure",
      action: "getScheduleSessions",
      error_code: "QUERY_FAILED",
    })
    return []
  }

  return data ?? []
}
