-- Migration: RPCs for session creation and rescheduling
-- Talitha Psicologia — Sprint 4 (Agenda e Lembretes)
--
-- These RPCs replace service_role usage in Server Actions for session
-- management. With INSERT/UPDATE REVOKE'd from authenticated on sessions
-- (ADR-0002 / AC2), all writes go through narrow SECURITY DEFINER RPCs
-- that validate authorization, ownership, and business rules.
--
-- Both functions follow the canonical pattern:
--   search_path fixed, auth.uid() validated, role from DB (fn_is_psychologist),
--   aal2 required, ownership checked, IS DISTINCT FROM for NULL-safety,
--   REVOKE triplo + GRANT explicit.

-- ============================================================
-- create_session: psychologist creates a therapy session
--
-- psychologist_id derived from auth.uid() — NEVER from parameter.
-- room_name generated by column DEFAULT (128 bits) — not accepted.
-- Conflict check considers duration (interval overlap).
-- ============================================================
CREATE OR REPLACE FUNCTION create_session(
  p_patient_id          UUID,
  p_scheduled_at        TIMESTAMPTZ,
  p_duration_minutes    INT DEFAULT 50,
  p_recurrence_group_id UUID DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid        UUID;
  v_session_id UUID;
  v_new_end    TIMESTAMPTZ;
BEGIN
  -- Auth gate
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Role gate (reads DB via SD helper — R13, no JWT trust)
  IF NOT fn_is_psychologist() THEN
    RAISE EXCEPTION 'Only the psychologist can create sessions';
  END IF;

  -- MFA gate
  IF (auth.jwt()->>'aal') IS DISTINCT FROM 'aal2' THEN
    RAISE EXCEPTION 'MFA required';
  END IF;

  -- Ownership: patient belongs to this psychologist
  IF NOT EXISTS (
    SELECT 1 FROM patients
    WHERE id = p_patient_id AND psychologist_id = v_uid
  ) THEN
    RAISE EXCEPTION 'Patient not found';
  END IF;

  -- scheduled_at must be in the future
  IF p_scheduled_at <= now() THEN
    RAISE EXCEPTION 'Session must be scheduled in the future';
  END IF;

  -- duration_minutes within reasonable range
  IF p_duration_minutes IS NULL OR p_duration_minutes < 15 OR p_duration_minutes > 180 THEN
    RAISE EXCEPTION 'Duration must be between 15 and 180 minutes';
  END IF;

  -- Conflict check: interval overlap with non-cancelled sessions
  -- Two intervals [A_start, A_end) and [B_start, B_end) overlap
  -- iff A_start < B_end AND A_end > B_start
  v_new_end := p_scheduled_at + (p_duration_minutes || ' minutes')::INTERVAL;

  IF EXISTS (
    SELECT 1 FROM sessions
    WHERE psychologist_id = v_uid
      AND status NOT IN ('cancelled', 'no_show')
      AND scheduled_at < v_new_end
      AND (scheduled_at + (duration_minutes || ' minutes')::INTERVAL) > p_scheduled_at
  ) THEN
    RAISE EXCEPTION 'Schedule conflict: another session overlaps this time slot';
  END IF;

  -- Insert — room_name comes from column DEFAULT (128-bit random)
  INSERT INTO sessions (
    patient_id, psychologist_id, scheduled_at,
    duration_minutes, recurrence_group_id
  ) VALUES (
    p_patient_id, v_uid, p_scheduled_at,
    p_duration_minutes, p_recurrence_group_id
  )
  RETURNING id INTO v_session_id;

  RETURN v_session_id;
END;
$$;

-- Canonical REVOKE triplo + GRANT
REVOKE EXECUTE ON FUNCTION create_session FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION create_session TO authenticated;

-- ============================================================
-- reschedule_session: psychologist moves a session to a new time
--
-- Only updates scheduled_at. The trigger fn_sessions_on_reschedule
-- handles room_name regeneration and waiting_since/admitted_at reset
-- automatically (BEFORE UPDATE, fires from within SD context).
-- ============================================================
CREATE OR REPLACE FUNCTION reschedule_session(
  p_session_id       UUID,
  p_new_scheduled_at TIMESTAMPTZ
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid     UUID;
  v_session RECORD;
  v_new_end TIMESTAMPTZ;
BEGIN
  -- Auth gate
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Role gate
  IF NOT fn_is_psychologist() THEN
    RAISE EXCEPTION 'Only the psychologist can reschedule sessions';
  END IF;

  -- MFA gate
  IF (auth.jwt()->>'aal') IS DISTINCT FROM 'aal2' THEN
    RAISE EXCEPTION 'MFA required';
  END IF;

  -- Load session
  SELECT id, psychologist_id, status, duration_minutes
  INTO v_session
  FROM sessions
  WHERE id = p_session_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Session not found';
  END IF;

  -- Ownership: session belongs to this psychologist
  IF v_session.psychologist_id IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'Not your session';
  END IF;

  -- Status: only scheduled/confirmed can be rescheduled
  IF v_session.status NOT IN ('scheduled', 'confirmed') THEN
    RAISE EXCEPTION 'Session in status % cannot be rescheduled', v_session.status;
  END IF;

  -- New time must be in the future
  IF p_new_scheduled_at <= now() THEN
    RAISE EXCEPTION 'New time must be in the future';
  END IF;

  -- Conflict check (exclude self)
  v_new_end := p_new_scheduled_at + (v_session.duration_minutes || ' minutes')::INTERVAL;

  IF EXISTS (
    SELECT 1 FROM sessions
    WHERE psychologist_id = v_uid
      AND id IS DISTINCT FROM p_session_id
      AND status NOT IN ('cancelled', 'no_show')
      AND scheduled_at < v_new_end
      AND (scheduled_at + (duration_minutes || ' minutes')::INTERVAL) > p_new_scheduled_at
  ) THEN
    RAISE EXCEPTION 'Schedule conflict: another session overlaps this time slot';
  END IF;

  -- Update only scheduled_at — trigger handles room_name + waiting state
  UPDATE sessions
  SET scheduled_at = p_new_scheduled_at
  WHERE id = p_session_id;
END;
$$;

-- Canonical REVOKE triplo + GRANT
REVOKE EXECUTE ON FUNCTION reschedule_session FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION reschedule_session TO authenticated;
